change workflows, remove qrcode

diff --git a/.github/workflows/build-docker-image.yml b/.github/workflows/build-docker-image.yml
--- a/.github/workflows/build-docker-image.yml
+++ b/.github/workflows/build-docker-image.yml
@@ -24,24 +24,14 @@ jobs:
         CI_COMMIT_MESSAGE=`echo $CI_COMMIT_MESSAGE | sed 's/\n//g'`
         CI_COMMIT_BRANCH=$GITHUB_REF_NAME
         CI_COMMIT_TIMESTAMP="${{ github.event.head_commit.timestamp }}"
-        KEY="${{ secrets.KEY }}"
-        PUSH_TIME=$(TZ=Asia/Shanghai date -d $CI_COMMIT_TIMESTAMP "+%Y-%m-%d %H:%M:%S")
         TIMEVERSION=$(TZ=Asia/Shanghai date -d $CI_COMMIT_TIMESTAMP "+%Y.%m.%d")
-        echo "PUSH_TIME=$PUSH_TIME" >> $GITHUB_ENV
         echo "CI_COMMIT_MESSAGE=$CI_COMMIT_MESSAGE" >> $GITHUB_ENV
         echo "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH" >> $GITHUB_ENV
         echo "CI_COMMIT_SHA=${{ github.event.head_commit.id }}" >> $GITHUB_ENV
-        echo "IMAGE_TAG_LATEST=lswl/vertex:latest" >> $GITHUB_ENV
+        echo "IMAGE_TAG_LATEST=blablabra/vertex:latest" >> $GITHUB_ENV
         echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
-        echo "IMAGE_TAG_BRANCH=lswl/vertex:$CI_COMMIT_BRANCH" >> $GITHUB_ENV
-        echo "IMAGE_TAG_TIMEVERSION=lswl/vertex:$TIMEVERSION" >> $GITHUB_ENV
-        echo "PUSH_TIME=$PUSH_TIME" >> $GITHUB_ENV
-        echo "KEY=$KEY" >> $GITHUB_ENV
-    - name: Push Start Message
-      run: |
-        curl --location --request POST 'https://vertex-push.lswl.workers.dev' \
-          --header 'Content-Type: application/json' \
-          --data-raw "{\"key\": \"$KEY\",\"time\": \"$PUSH_TIME\",\"message\": \"$CI_COMMIT_MESSAGE\",\"branch\": \"$CI_COMMIT_BRANCH\",\"sha1\": \"${CI_COMMIT_SHA:0:12}\", \"type\": \"start\"}"
+        echo "IMAGE_TAG_BRANCH=blablabra/vertex:$CI_COMMIT_BRANCH" >> $GITHUB_ENV
+        echo "IMAGE_TAG_TIMEVERSION=blablabra/vertex:$TIMEVERSION" >> $GITHUB_ENV
     - name: Install Dependencies
       run: |
         npm i --save-dev
@@ -91,16 +81,11 @@ jobs:
         cd docker
         sed -i 's/COMMIT_ID/'$CI_COMMIT_SHA'/' Dockerfile
         ls src/static
-        docker pull --platform linux/arm64 lswl/vertex:latest || echo 'fail'
-        docker pull --platform linux/amd64 lswl/vertex:latest || echo 'fail'
+        docker pull --platform linux/arm64 blablabra/vertex:latest || echo 'fail'
+        docker pull --platform linux/amd64 blablabra/vertex:latest || echo 'fail'
     - name: Build Docker Images
       working-directory: ./docker
       run: |
-        docker buildx build --platform linux/amd64,linux/arm64 --cache-from lswl/vertex --tag $IMAGE_TAG_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 . --push
-        docker buildx build --platform linux/amd64,linux/arm64 --cache-from lswl/vertex --tag $IMAGE_TAG_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 . --push
-        docker buildx build --platform linux/amd64,linux/arm64 --cache-from lswl/vertex --tag $IMAGE_TAG_TIMEVERSION --build-arg BUILDKIT_INLINE_CACHE=1 . --push
-    - name: Push Finish Message
-      run: |
-        curl --location --request POST 'https://vertex-push.lswl.workers.dev' \
-          --header 'Content-Type: application/json' \
-          --data-raw "{\"key\": \"$KEY\",\"time\": \"$PUSH_TIME\",\"message\": \"$CI_COMMIT_MESSAGE\",\"branch\": \"$CI_COMMIT_BRANCH\",\"sha1\": \"${CI_COMMIT_SHA:0:12}\"}"
+        docker buildx build --platform linux/amd64,linux/arm64 --cache-from blablabra/vertex --tag $IMAGE_TAG_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 . --push
+        docker buildx build --platform linux/amd64,linux/arm64 --cache-from blablabra/vertex --tag $IMAGE_TAG_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 . --push
+        docker buildx build --platform linux/amd64,linux/arm64 --cache-from blablabra/vertex --tag $IMAGE_TAG_TIMEVERSION --build-arg BUILDKIT_INLINE_CACHE=1 . --push
